// <auto-generated />
using BackupSync.Core.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackupSync.Core.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251222205251_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("BackupSync.Core.Models.Device", b =>
                {
                    b.Property<int>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastKnownLabel")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastKnownLetter")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserGivenName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("VolumeSerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("BackupSync.Core.Models.JobExclusion", b =>
                {
                    b.Property<int>("JobExclusionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncJobId")
                        .HasColumnType("INTEGER");

                    b.HasKey("JobExclusionId");

                    b.HasIndex("SyncJobId");

                    b.ToTable("JobExclusions");
                });

            modelBuilder.Entity("BackupSync.Core.Models.SyncJob", b =>
                {
                    b.Property<int>("SyncJobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConflictPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DestPath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeviceId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("JobType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrphanPolicy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("SyncJobId");

                    b.HasIndex("DeviceId");

                    b.ToTable("SyncJobs");
                });

            modelBuilder.Entity("BackupSync.Core.Models.JobExclusion", b =>
                {
                    b.HasOne("BackupSync.Core.Models.SyncJob", "SyncJob")
                        .WithMany("Exclusions")
                        .HasForeignKey("SyncJobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SyncJob");
                });

            modelBuilder.Entity("BackupSync.Core.Models.SyncJob", b =>
                {
                    b.HasOne("BackupSync.Core.Models.Device", "Device")
                        .WithMany("SyncJobs")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("BackupSync.Core.Models.Device", b =>
                {
                    b.Navigation("SyncJobs");
                });

            modelBuilder.Entity("BackupSync.Core.Models.SyncJob", b =>
                {
                    b.Navigation("Exclusions");
                });
#pragma warning restore 612, 618
        }
    }
}
